[wokwi]
version = 1
elf = ".pio/build/upesy_wroom/firmware.elf"
firmware = ".pio/build/upesy_wroom/firmware.bin"

# Forward http://localhost:8180 to port 80 on the simulated ESP32:
[[net.forward]]
from = "localhost:8180"
to = "target:80"
